
[[constraint]]
  branch = "master"
  name = "github.com/banzaicloud/hollowtrees"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
[[constraint]]
  name = "github.com/ericchiang/k8s"
  version = "0.4.0"
